name=GitHubOTA
version=0.1.0
author=Al-Zhilin <alekseyzh5@gmail.com>
maintainer=Al-Zhilin <alekseyzh5@gmail.com>
sentence=Библиотека автономного OTA обновления для ESP32/ESP8266
paragraph=Библиотека автономного OTA обновления для ESP32/ESP8266: проверяет релизы GitHub на наличие новой версии, загружает ее с проверкой MD5 и устанавливает с автоматическим откатом при ошибках на поддерживаемых платформах
category=Communication
url=https://github.com/Al-Zhilin/GitHubOTA
architectures=esp32,esp8266
